### ISSUE TITLE
Challenge with sending messages to large groups in mHero

### ISSUE THREAD

**Issue by cloehr651** [intrahealth/emNutt#13]
In the Kenya instance it is possible to send out messages to just a few people but sending to a large group is not working.

**Comment by cloehr651** [comment]
This is has been fixed. the page for sending messages is now displaying only those records that has phone numbers and the phone numbers are valid. Also auto resending of failed messages have been added into mHero.

**Comment by cloehr651** [comment]
@lkwirica and @njugunask can you confirm whether this has been fixed? If so, please move to the "Done" column of the project.

**Comment by njugunask** [comment]
Hi Caitlin,

This will be confirmed tomorrow once approved message(s) are sent via mHero.

Best,

Stanley.

**Comment by lkwirica** [comment]
@Caitlin Loehr<mailto:cloehr@intrahealth.org> under my account in projects, I don’t seem to have this view.

I can only open, close, assign etc.

Kind regards,

Loise Kwirica | HRIS Officer
HRH Kenya Mechanism
USAID Partner

IntraHealth International<http://www.intrahealth.org/> | Because Health Workers Save Lives.
P.O. Box 66726 - 00800
Ring Road/Lower Kabete Rd, Westlands, Nairobi, Kenya
9 West Building, 4th Floor,
t. +254 (020) 3645000 | m. +254 (0729) 097511
Email: lkwirica@intrahealth.org<mailto:lkwirica@intrahealth.org>

[cid:image002.png@01D70AAC.9EE96EB0]

“If we have data, let’s look at data. If all we have are opinions, let’s go with mine .” — Jim Barksdale
