### ISSUE TITLE
Duplication of records 

### ISSUE THREAD

**Issue by lkwirica** [intrahealth/emNutt#20]
If a contact exisits in Rapidpro and on iHRIS, two records are created for the same person especially if the phone number format is different. This means that we will have numerous duplicates on mHero. e.g. janet wanjiku karimi,Michael Oluoch Ogalo

**Comment by cloehr651** [comment]
This is the reason we warned against using RapidPro only - since there was no auto-syncing between RapidPro and iHRIS, any changes in one system needed to be made in both systems so now we have cleaning up to do because you used RapidPro only for so long.

@ashaban, are there any scripts that can help either identify duplicates and/or de-duplicate records?

**Comment by ashaban** [comment]
i will need to check or write one for Kenya @cloehr651

**Comment by njugunask** [comment]
Serious data cleaning needs to be done, numerous duplicates / some records share the same phone numbers

**Comment by lkwirica** [comment]
Hi Stanley,

Please note some of the issues on the tracker were closed a while back. We’re only reviewing the open issues:

***@***.***D762A9.9B5A2410]

Kind regards,

Loise Kwirica | HRIS Officer
HRH Kenya Mechanism
USAID Partner

IntraHealth International<http://www.intrahealth.org/> | Because Health Workers Save Lives.
P.O. Box 66726 - 00800
Ring Road/Lower Kabete Rd, Westlands, Nairobi, Kenya
9 West Building, 4th Floor,
t. +254 (020) 3645000 | m. +254 (0729) 097511
Email: ***@***.******@***.***>

***@***.***D762A9.B2105990]

“If we have data, let’s look at data. If all we have are opinions, let’s go with mine .” — Jim Barksdale
