### ISSUE TITLE
Fluctuating numbers for contacts 

### ISSUE THREAD

**Issue by njugunask** [intrahealth/emNutt#39]
The numbers for contacts are varying, there is an addition of 2,821 contacts to what the system had, 58,523. Kindly check why this the case.

**Comment by cloehr651** [comment]
Can you please provide more details? Which number are you looking at (what page)? When are you noticing that it's different? What do you believe the number of contacts should be?

**Comment by njugunask** [comment]
Hi Caitlin, when sending messages in mHERO from the 'send message' tab it gives the total contacts that the selected flow should go to herein 58, 523 that we have been working with. However, that number as today is 61,344. See attached screenshot.
<img width="941" alt="contact-list in mHERO" src="https://user-images.githubusercontent.com/77440202/109326779-a54ab280-7868-11eb-8e11-91d296558c33.png">

**Comment by ashaban** [comment]
@njugunask the database has a total of 121,724 records, not all of these records are displayed on the send message page because some of them have wrong phone numbers. However, if any of the records with invalid phone number get cleaned from iHRIS v4, they will automatically show up on the page for sending messages, and the total records on the send message page will automatically increase. So you should expect the number to be increasing.

One other thing to note, if a practitioner get subscribed to multiple groups, they will show up twice to allow you to select a group to send message if you are to send messages by groups. an example can be, if Ally belongs to group 1 and group 2, then the report will show two rows for Ally, all rows will have same details except group name, one row will have group 1 and the second row will have group2. When sending message, only one row of the two will be sent message and not all, you should not worry about dupplicate message for this case.

One other thing to note, the send message page was designed for sending messages and not viewing how many records the database has. If you are to check the number of records you have then the search people page is the right place for you to check.

**Comment by lkwirica** [comment]
@ashaban I think that the total number of records is still an issue as we have not had any changes in any contacts being added or removed on Rapidpro/mHero, but the numbers keep fluctuating, from 21k, 58k and now 61k. 

As per the March 1st message sent out , I believe all rows got sent the message, as evidenced by the duplicates

**Comment by lkwirica** [comment]
@njugunask this issue is pending

**Comment by njugunask** [comment]
Hi Loise,

Good evening. Will reopen it asap!

Best,

Stanley.

**Comment by cloehr651** [comment]
@lkwirica and @njugunask can you clarify what the current issue is?
