### ISSUE TITLE
Discrepancies on the no. of messages sent out in the reports 

### ISSUE THREAD

**Issue by lkwirica** [intrahealth/emNutt#51]
Here's the stats as per the message sending summary: 
![image](https://user-images.githubusercontent.com/77771356/112268195-a57f7780-8c87-11eb-9a09-b182d28af478.png)

![image](https://user-images.githubusercontent.com/77771356/112268303-cea00800-8c87-11eb-8be7-6ba5a582a9fb.png)
Here are the actual stats as per Africastalking

**Comment by cloehr651** [comment]
@lkwirica are you asking about why there is a difference between the number sent in the mHero report vs the number sent in the Africa's Talking report? Or differences in the number sent from day to day?

If the former, I believe this is because the mHero report shows messages sent from mHero to Africa's Talking but a message can fail to be sent out from Africa's Talking out to the recipients so the Africa's Talking reports show the number that Africa's Talking was able to send to recipients. @ashaban is this correct?

**Comment by lkwirica** [comment]
Closing this issue to track related messaging/contacts issues under issue #40
